/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopSplatRouteImport } from './routes/workshop.$'

const WorkshopSplatRoute = WorkshopSplatRouteImport.update({
  id: '/workshop/$',
  path: '/workshop/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/workshop/$': typeof WorkshopSplatRoute
}
export interface FileRoutesByTo {
  '/workshop/$': typeof WorkshopSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/workshop/$': typeof WorkshopSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/workshop/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/workshop/$'
  id: '__root__' | '/workshop/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkshopSplatRoute: typeof WorkshopSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop/$': {
      id: '/workshop/$'
      path: '/workshop/$'
      fullPath: '/workshop/$'
      preLoaderRoute: typeof WorkshopSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WorkshopSplatRoute: WorkshopSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
